### ISSUE TITLE
'Values' object has no attribute 'syntax_highlight'

### ISSUE THREAD

**Issue by mondeja** [JulienPalard/pospell#21]
Im getting next error running v1.0.7 in `python-docs-es`:

```
Traceback (most recent call last):
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/statemachine.py", line 310, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/statemachine.py", line 1156, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    self.next_line()
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/statemachine.py", line 313, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mondeja/files/code/python-docs-es/venv/bin/pospell", line 8, in <module>
    sys.exit(main())
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/pospell.py", line 381, in main
    errors = spell_check(
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/pospell.py", line 296, in spell_check
    texts_for_hunspell[po_file] = po_to_text(str(po_file), drop_capitalized)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/pospell.py", line 190, in po_to_text
    buffer.append(clear(strip_rst(entry.msgstr), drop_capitalized, po_path=po_path))
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/pospell.py", line 138, in strip_rst
    parser.parse(line, document)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/statemachine.py", line 248, in run
    result = state.eof(context)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2712, in eof
    self.blank(None, context, None)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2703, in blank
    paragraph, literalnext = self.paragraph(
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 646, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 789, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 886, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/home/mondeja/files/code/python-docs-es/venv/lib/python3.8/site-packages/docutils/parsers/rst/roles.py", line 335, in code_role
    inliner.document.settings.syntax_highlight)
AttributeError: 'Values' object has no attribute 'syntax_highlight'
```

### Minimal reproducible example

```po
msgid "Un rôle de code :code:`object().__str__`"
msgstr "A code role :code:`object().__str__`."
```

Seems that adding `"syntax_highlight": "none"`, `"syntax_highlight": "short"` or ``"syntax_highlight": "long"`` in `docutils.frontend.Values` it's fixed, but I'm not totally secure of the side effects of this because after update to v1.0.7, adding this setting property I'm getting `23751` number of errors in `python-docs-es` against the `570` of v1.0.6.

Is the change in v1.0.7 a breaking change in the preprocessing step of pospell? Thanks for your work.

**Comment by JulienPalard** [comment]
Sorry for that, can you try 1.0.8?

**Comment by mondeja** [comment]
Sorry but this implementation is totally a breaking change.

If I run v1.0.8 for multiple files with a glob like `**/*.po` with `--glob **/*.po`, if an error is found in a file (for example, the word `th` in `using/foo.po`), other lines that match `th` in whatever other files are marked as errors. As a result, I have a lot of `th`, `min`, `sp`, `out`, `semi`, `thin`... marked in files where the errors are not in.

This works well executing pospell for a file, but not at all running pospell for multiple files using globs.

Run one `hunspell` command for all files might be faster, but it's very hard to debug where errors are coming from.

**Comment by JulienPalard** [comment]
That's what I feared. But I tried on python-docs-fr and did not spot the issue so I was confident, but it was a bad test, as we have no errors, the bug cannot trigger :(

**Comment by JulienPalard** [comment]
I'll try to fix this by using the `hunspell -a` flag. Hope I can do something.

**Comment by JulienPalard** [comment]
@mondeja Can you try 1.0.9? Sorry for the roller coaster :]

**Comment by mondeja** [comment]
Now it's working like a charm! Without false positives nor the errors redundancy of 1.0.6.

Great code and thank you so much @JulienPalard :+1:
